Repository CruGlobal/godtools-android, pull requests merged in 2019-11, with the labels that each got.

#639 remove the GoogleAnalyticsService
  build.gradle
  library/analytics/build.gradle
  library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsDispatcher.java
  library/analytics/src/main/java/org/cru/godtools/analytics/GoogleAnalyticsService.java
Labels: dontmerge

#741 GT-601 : include footer at bottom of cards to indicate next card
  library/base/src/main/java/org/cru/godtools/base/util/LocaleUtils.java
  ui/tract-renderer/build.gradle
  ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/CardViewHolder.java
  ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/PageViewHolder.java
  ui/tract-renderer/src/main/res/layout/tract_content_card.xml
  ui/tract-renderer/src/main/res/values/strings_tract_renderer.xml
Labels: Ready to Review

#743 GT-631 : update tool info home design (Phase 1)
  app/build.gradle
  app/src/main/java/org/cru/godtools/fragment/ToolDetailsFragment.java
  app/src/main/java/org/cru/godtools/util/ActivityUtils.kt
  app/src/main/java/org/keynote/godtools/android/activity/MainActivity.java
  app/src/main/res/layout/fragment_tool_details.xml
  app/src/main/res/layout/tool_detail_text_view.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  ui/base/src/main/res/drawable/btn_colored.xml
  ui/base/src/main/res/values/styles_widgets.xml
Labels: Ready to Review, UI/UX

#755 update org.jetbrain:annotations
  build.gradle
Labels: dependencies

#760 GT-601 : Requested Changes from QA
  ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/CardViewHolder.java
  ui/tract-renderer/src/main/res/layout/tract_content_card.xml
Labels: Ready to Review
